version: '3.7'

services:
  event-generator:
    container_name: event-generator
    depends_on:
      - kafka
    build:
      context: './event-generator'
    ports:
      - "8080:8080"
    environment:
      - "SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:29092"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      - "ZOOKEEPER_CLIENT_PORT=2181"
      - "ZOOKEEPER_TICK_TIME=2000"

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - "KAFKA_BROKER_ID=1"
      - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT"
      - "KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092, PLAINTEXT_HOST://localhost:9092"
      - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      - "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1"
      - "KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1"
      - "KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1"

  clickhouse-server:
    image: yandex/clickhouse-server
    container_name: ch-server
    volumes:
      - './clickhouse-init/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql'
    depends_on:
      - kafka
    links:
      - kafka
    ports:
      - "8123:8123"

  clickhouse-client:
    image: yandex/clickhouse-client
    container_name: ch-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity